
package za.co.dladle.paygate;

import za.co.dladle.paygate.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PayHOST", targetNamespace = "http://www.paygate.co.za/PayHOST")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    za.co.dladle.paygate.ObjectFactory.class
})
public interface PayHOST {


    /**
     * 
     * @param singlePayoutRequest
     * @return
     *     returns za.co.dladle.paygate.SinglePayoutResponse
     */
    @WebMethod(operationName = "SinglePayout")
    @WebResult(name = "SinglePayoutResponse", targetNamespace = "http://www.paygate.co.za/PayHOST", partName = "SinglePayoutResponse")
    public SinglePayoutResponse singlePayout(
            @WebParam(name = "SinglePayoutRequest", targetNamespace = "http://www.paygate.co.za/PayHOST", partName = "SinglePayoutRequest")
                    SinglePayoutRequest singlePayoutRequest);

    /**
     * 
     * @param singlePaymentRequest
     * @return
     *     returns za.co.dladle.paygate.SinglePaymentResponse
     */
    @WebMethod(operationName = "SinglePayment")
    @WebResult(name = "SinglePaymentResponse", targetNamespace = "http://www.paygate.co.za/PayHOST", partName = "SinglePaymentResponse")
    public SinglePaymentResponse singlePayment(
            @WebParam(name = "SinglePaymentRequest", targetNamespace = "http://www.paygate.co.za/PayHOST", partName = "SinglePaymentRequest")
                    SinglePaymentRequest singlePaymentRequest);

    /**
     * 
     * @param singleFollowUpRequest
     * @return
     *     returns za.co.dladle.paygate.SingleFollowUpResponse
     */
    @WebMethod(operationName = "SingleFollowUp")
    @WebResult(name = "SingleFollowUpResponse", targetNamespace = "http://www.paygate.co.za/PayHOST", partName = "SingleFollowUpResponse")
    public SingleFollowUpResponse singleFollowUp(
            @WebParam(name = "SingleFollowUpRequest", targetNamespace = "http://www.paygate.co.za/PayHOST", partName = "SingleFollowUpRequest")
                    SingleFollowUpRequest singleFollowUpRequest);

    /**
     * 
     * @param singleVaultRequest
     * @return
     *     returns za.co.dladle.paygate.SingleVaultResponse
     */
    @WebMethod(operationName = "SingleVault")
    @WebResult(name = "SingleVaultResponse", targetNamespace = "http://www.paygate.co.za/PayHOST", partName = "SingleVaultResponse")
    public SingleVaultResponse singleVault(
            @WebParam(name = "SingleVaultRequest", targetNamespace = "http://www.paygate.co.za/PayHOST", partName = "SingleVaultRequest")
                    SingleVaultRequest singleVaultRequest);

    /**
     * 
     * @param pingRequest
     * @return
     *     returns za.co.dladle.paygate.PingResponse
     */
    @WebMethod(operationName = "Ping")
    @WebResult(name = "PingResponse", targetNamespace = "http://www.paygate.co.za/PayHOST", partName = "PingResponse")
    public PingResponse ping(
            @WebParam(name = "PingRequest", targetNamespace = "http://www.paygate.co.za/PayHOST", partName = "PingRequest")
                    PingRequest pingRequest);

}
